version: "3"

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - .:/app
    entrypoint: /run_server.sh
    ports:
      - "${secrets.WEB_PORTS}"
    environment:
      - POSTGRES_NAME=${secrets.POSTGRES_DB}
      - POSTGRES_USER=${secrets.POSTGRES_USER}
      - POSTGRES_PASSWORD=${secrets.POSTGRES_PASSWORD}
    depends_on:
      - db

  db:
    container_name: postgres_db
    image: postgres
    environment:
      POSTGRES_USER: ${secrets.POSTGRES_USER}
      POSTGRES_PASSWORD: ${secrets.POSTGRES_PASSWORD}
      PGDATA: /data/postgresc
    volumes:
      - postgres:/data/postgres
    ports:
      - "${secrets.POSTGRES_PORTS}"
    restart: unless-stopped

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"

  celery:
    restart: always
    build:
      context: ./
    volumes:
      - .:/app
    entrypoint: /run_celery.sh
    depends_on:
      - db
      - rabbitmq
      - app

volumes:
  postgres: