version: "3"

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile_test
    volumes:
      - .:/app
    entrypoint: /run_tests.sh
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - db

  db:
    container_name: postgres_db
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgresc
    volumes:
      - postgres:/data/postgres
    ports:
      - "54321:5433"
    restart: unless-stopped

volumes:
  postgres: