version: "3"

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile_test
    volumes:
      - .:/app
    entrypoint: /run_tests.sh
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=innotter_test
      - POSTGRES_USER=innotter_test
      - POSTGRES_PASSWORD=admin
    depends_on:
      - db

  db:
    container_name: postgres_db
    image: postgres
    environment:
      POSTGRES_USER: innotter_test
      POSTGRES_PASSWORD: admin
      PGDATA: /data/postgresc
    volumes:
      - postgres:/data/postgres
    ports:
      - "54321:5432"
    restart: unless-stopped

volumes:
  postgres: