# Generated by Django 4.1.2 on 2022-10-14 06:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_remove_post_id_post_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
