# Generated by Django 4.1.2 on 2022-11-03 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
