# Generated by Django 4.1.2 on 2022-11-06 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_remove_post_likes_likes_post_likes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
