# Generated by Django 4.1.2 on 2022-11-06 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0021_like_like_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
