# Generated by Django 4.1.2 on 2022-11-06 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0023_like_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
