# Generated by Django 4.1.2 on 2022-10-14 06:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_remove_page_id_remove_tag_id_tag_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=30, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
