# Generated by Django 4.1.2 on 2022-10-14 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_alter_page_uuid_alter_tag_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
