# Generated by Django 4.1.2 on 2022-10-13 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AddField(
            model_name='user',
            name='uuid',
            field=models.CharField(default='', editable=False, max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
