# Generated by Django 4.1.2 on 2022-10-13 09:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_id_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
