name: Django Tests

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
  push:
    branches:
      - dev
      - master

  pull_request:
    branches:
      - dev
      - master

jobs:
  build:
    environment: $ {{ input.environment }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the stack with tests
#      - environment:
#          POSTGRES_NAME: ${{ secrets.POSTGRES_DB }}
#          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
#          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
#          DEBUG: ${{ secrets.DEBUG }}
#          SERVER_NAMES: ${{ secrets.SERVER_NAMES }}
#          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: sudo docker-compose -f ./docker-compose.test.yml up