name: Django Tests

on:
  push:
    branches:
      - dev
      - master
  pull_request:
    branches:
      - dev
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      POSTGRES_NAME: ${{ secrets.POSTGRES_DB }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      DEBUG: ${{ secrets.DEBUG }}
      SERVER_NAMES: ${{ secrets.SERVER_NAMES }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
    steps:
      - uses: actions/checkout@v3
      - name: Add environment variables to .env
        run: |
          echo SECRET_KEY=${{ secrets.SECRET_KEY }} >> .env
          echo POSTGRES_NAME=${{ secrets.POSTGRES_DB }} >> .env
          echo POSTGRES_USER=${{ secrets.POSTGRES_USER }} >> .env
          echo POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} >> .env
          echo DEBUG=${{ secrets.DEBUG }} >> .env
          echo SERVER_NAMES=${{ secrets.SERVER_NAMES }} >> .env
      - name: Build the stack with tests
        run: sudo docker-compose -f ./docker-compose.test.yml up