name: Django Tests

on:
  push:
    branches:
      - dev
      - master

  pull_request:
    branches:
      - dev
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    #    strategy:
    #      matrix:
    #        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Run docker-compose.yml
        run: sudo docker-compose up -d
      #      - name: Set up Python ${{ matrix.python-version }}
      #        uses: actions/setup-python@v4
      #        with:
      #          python-version: ${{ matrix.python-version }}
      #      - name: Install poetry
      #        run: |
      #          pip install poetry
      #      - name: Install dependencies
      #        run: |
      #          poetry install -v
      - name: Django Testing
        run: poetry run python3 manage.py test