name: Django Tests

on:
  push:
    branches:
      - dev
      - master
  pull_request:
    branches:
      - dev
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      POSTGRES_NAME: ${{ secrets.POSTGRES_DB }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      DEBUG: ${{ secrets.DEBUG }}
      SERVER_NAMES: ${{ secrets.SERVER_NAMES }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
    steps:
      - uses: actions/checkout@v3
      - name: Build the stack with tests
        env:
          POSTGRES_NAME: ${{ env.POSTGRES_DB }}
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
          DEBUG: ${{ env.DEBUG }}
          SERVER_NAMES: ${{ env.SERVER_NAMES }}
          SECRET_KEY: ${{ env.SECRET_KEY }}
        run: sudo docker-compose -f ./docker-compose.test.yml up