name: Django Tests

on:
  push:
    branches:
      - dev
      - master

  pull_request:
    branches:
      - dev
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      POSTGRES_NAME: ${{ secrets.POSTGRES_DB }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}

    steps:
      - uses: actions/checkout@v3
      - name: Build the stack
        run: sudo docker-compose up

#      - name: Django Testing
#        run: sudo docker-compose run --rm app sh -c "python manage.py test"