name: Django Tests

on:
  push:
    branches:
      - dev
      - master

  pull_request:
    branches:
      - dev
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      POSTGRES_NAME: ${{ secrets.POSTGRES_DB }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}

    steps:
      - uses: actions/checkout@v3
      - name: Build the stack
        run: sudo docker-compose -f docker-compose.test.yml up -d --build

      - name: Django Testing
        run: python manage.py test